dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
cache:
directories:
- $HOME/.m2
script:
- cd restaurant-manager/
- mvn clean install
- mvn clean test jacoco:report coveralls:report
